### ISSUE TITLE
error in running the included examples

### ISSUE THREAD

**Issue by sawstory** [choderalab/yank#1199]
I have the following error if i run any of the included examples, any advice? Thanks
Omar
```
(base) om@om-SYS-4028GR-TR:~/yank-examples/examples/binding/t4-lysozyme$ yank selftest


YANK Selftest
-------------
Yank Version 0.25.2 

Available OpenMM platforms:
    0 Reference
    1 CPU
    2 CUDA
    3 OpenCL



Valid OpenEye install not found
Not required, but please check install if you expected it


Checking GPU Computed Mode (if present)...
Found 6 NVIDIA GPUs in the following modes: [Default, Default, Default, Default, Default, Default]
These should all be in shared/Default mode for YANK to use them
YANK Selftest complete.
Thank you for using YANK!

(base) om@om-SYS-4028GR-TR:~/yank-examples/examples/binding/t4-lysozyme$ sh run-all-ligands-explicit.sh 
Running simulation...
found unknown parameter number_of_iterations
Traceback (most recent call last):
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/experiment.py", line 1191, in _validate_options
    special_conversions=special_conversions)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/utils.py", line 1058, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/om/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/commands/script.py", line 147, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/experiment.py", line 591, in __init__
    self.parse(script)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/experiment.py", line 681, in parse
    validate_general_options=True))
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/experiment.py", line 1193, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations
Analyzing data...
Traceback (most recent call last):
  File "/home/om/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/commands/analyze.py", line 107, in dispatch
    from .. import utils, analyze
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/analyze.py", line 49, in <module>
    yank_registry = mmtools.multistate.default_observables_registry
AttributeError: module 'openmmtools' has no attribute 'multistate'
(base) om@om-SYS-4028GR-TR:~/yank-examples/examples/binding/t4-lysozyme$ 
```

**Comment by jchodera** [comment]
Thanks for reporting this! 

The examples in https://github.com/choderalab/yank-examples have unfortunately drifted out of sync with the latest YAML syntax. We'll make sure to get those updated.

@andrrizzi : Updating those examples would be important for project continuity in yank development, so it would be great if you and @jaimergp had a chance to go through them and update them this week!

**Comment by andrrizzi** [comment]
Hi @sawstory . As John said, the examples in those repo are out of date. The option `number_of_iterations` was substituted by `default_number_of_iterations` when we added support for samplers. That should fix the error that you posted.

**Comment by sawstory** [comment]
still have the same error!
This is from yaml file
# Set the general options of our simulation
options:
  minimize: yes
  verbose: yes
  default_number_of_iterations: 500
  temperature: 300*kelvin
  pressure: null
  output_dir: p-xylene-implicit-output

and this is the error
(base) om@om-SYS-4028GR-TR:~/anaconda3/share/yank/examples/binding/t4-lysozyme$ sh run-p-xylene-implicit.sh 
Running simulation...
2019-12-02 11:54:03,035: Setting CUDA platform to use precision model 'mixed'.
2019-12-02 11:54:03,182: Single node: executing <function ExperimentBuilder._check_resume at 0x7f71a1cb8560>
2019-12-02 11:54:03,183: Running _setup_molecules serially.
2019-12-02 11:54:03,660: Fixing net charge from -2.000000000015878e-06 to 4.163336342344337e-17
2019-12-02 11:54:03,662: Running get_system serially.
2019-12-02 11:54:03,663: Setting up the systems for t4-lysozyme and p-xylene using solvent GBSA
2019-12-02 11:54:03,663: Setting up solvent phase
2019-12-02 11:54:03,832: Setting up complex phase
2019-12-02 11:54:04,641: WARNING - yank.pipeline - TLeap: The unperturbed charge of the unit: 8.000000 is not zero.
2019-12-02 11:54:04,641: WARNING - yank.pipeline - TLeap: The unperturbed charge of the unit: 8.000000 is not zero.
2019-12-02 11:54:04,642: Single node: executing <function ExperimentBuilder._generate_yaml at 0x7f71a1cb8c20>
2019-12-02 11:54:04,651: Running _generate_experiment_protocol serially.
2019-12-02 11:54:04,653: DSL string for the ligand: "resname MOL"
2019-12-02 11:54:04,653: DSL string for the solvent: "auto"
2019-12-02 11:54:04,653: Reading phase complex
2019-12-02 11:54:04,654: prmtop: p-xylene-implicit-output/setup/systems/t4-xylene/complex.prmtop
2019-12-02 11:54:04,654: inpcrd: p-xylene-implicit-output/setup/systems/t4-xylene/complex.inpcrd
Traceback (most recent call last):
  File "/home/om/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/commands/script.py", line 155, in dispatch
    yaml_builder.run_experiments(write_status=write_status)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/experiment.py", line 751, in run_experiments
    completed[exp_index] = self._run_experiment(exp, write_status=write_status)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/experiment.py", line 3247, in _run_experiment
    built_experiment = self._build_experiment(experiment_path, experiment)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/experiment.py", line 3154, in _build_experiment
    sampler = self._create_experiment_sampler(experiment, mc_atoms)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/experiment.py", line 2990, in _create_experiment_sampler
    return schema.call_sampler_constructor(constructor_description)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/schema/validator.py", line 469, in call_sampler_constructor
    return call_constructor(mmtools.multistate.MultiStateSampler, constructor_description,
AttributeError: module 'openmmtools' has no attribute 'multistate'
Analyzing data...
Traceback (most recent call last):
  File "/home/om/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/commands/analyze.py", line 107, in dispatch
    from .. import utils, analyze
  File "/home/om/anaconda3/lib/python3.7/site-packages/yank-0.25.2-py3.7.egg/yank/analyze.py", line 49, in <module>
    yank_registry = mmtools.multistate.default_observables_registry
AttributeError: module 'openmmtools' has no attribute 'multistate'

**Comment by jchodera** [comment]
@andrrizzi @jaimergp can you two find time this week to go through and update yank-examples?

**Comment by andrrizzi** [comment]
Hi @sawstory . That's a different error that is unrelated to the YAML file. It happens on analysis. How did you install yank? Can you copy-paste here the result of `conda list`?

**Comment by sawstory** [comment]
i have a lot of trouble installing yank and get the self test  pass, the issue is that i use the recommended conda install -c omnia yank, but it install old version of yank which is 23.something and selftest fail , so i then installed version 25.2 from source which only update the yank part and then do the same for openmmtools to update it from 17.0 to 19.0. then the selftest pass but the examples give error. so i hope to fix the conda instal method as any beginner will reach dead end with that way of installation. here is the conda list

**Comment by jaimergp** [comment]
Given the paths to your YANK installation, it seems that you are installing YANK in the base environment of an Anaconda installation. Depending on how old this installation is, this can force `conda` to solve the dependency graph in a way that only old YANK versions can satisfy because the existing packages would impose some restraints on new additions to the environment.

Also, although you compiled latest YANK from source, its dependencies might be still outdated due to the environment constraints.

I'd suggest creating a new environment for YANK (and other packages you might need in your project) with `conda create`.

**Comment by jaimergp** [comment]
Also, this might be the cause to https://github.com/choderalab/yank/issues/1183.

**Comment by sawstory** [comment]
Thanks for help , can you please continue with  me to resolve this
I uninstalled Anaconda and reinstalled it
then i create new environment called dyanmics and then used conda install -c omnia yank but got this error

(base) tryinlin@tryinlin-desktop:~$ conda create --name dynamics python=3.7 -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/tryinlin/anaconda3/envs/dynamics

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.10.16 |                0         131 KB
    openssl-1.1.1d             |       h7b6447c_3         3.7 MB
    pip-19.3.1                 |           py37_0         1.9 MB
    python-3.7.5               |       h0371630_0        32.2 MB
    setuptools-42.0.1          |           py37_0         670 KB
    sqlite-3.30.1              |       h7b6447c_0         1.9 MB
    ------------------------------------------------------------
                                           Total:        40.5 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2019.10.16-0
  certifi            pkgs/main/linux-64::certifi-2019.9.11-py37_0
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1d-h7b6447c_3
  pip                pkgs/main/linux-64::pip-19.3.1-py37_0
  python             pkgs/main/linux-64::python-3.7.5-h0371630_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  setuptools         pkgs/main/linux-64::setuptools-42.0.1-py37_0
  sqlite             pkgs/main/linux-64::sqlite-3.30.1-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.33.6-py37_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3



Downloading and Extracting Packages
python-3.7.5         | 32.2 MB   | ##################################### | 100% 
pip-19.3.1           | 1.9 MB    | ##################################### | 100% 
ca-certificates-2019 | 131 KB    | ##################################### | 100% 
openssl-1.1.1d       | 3.7 MB    | ##################################### | 100% 
setuptools-42.0.1    | 670 KB    | ##################################### | 100% 
sqlite-3.30.1        | 1.9 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate dynamics
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) tryinlin@tryinlin-desktop:~$ conda activate dynamics
(dynamics) tryinlin@tryinlin-desktop:~$ conda install -c omnia yank
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining backports.shutil_get_terminal_size:  37%|▎| 81/220 [00:46<01:02,  2.21Examining hdf5:  37%|█████████▋                | 82/220 [00:46<01:02,  2.21it/s]Examining backports.functools_lru_cache:  55%|▌| 121/220 [00:46<00:44,  2.21it/sExamining jpeg:  55%|█████████████▊           | 122/220 [00:46<00:44,  2.21it/s]Examining python:  85%|███████████████████▌   | 187/220 [00:46<00:14,  2.21it/s]
Comparing specs that have this dependency:   0%|          | 0/2 [00:00<?, ?it/s]
Finding shortest conflict path for python[version='>=3.7,<3.8.0a0']:  50%|▌| 1/2/                                                                               Finding shortest conflict path for python-dateutil:   0%| | 0/19 [00:00<?, ?it/sFinding shortest\ onflict path for ipython[version='>=4.0']:   5%| | 1/19 [00:00Finding shortest conflict path for ipython[version='>=4.0']:  11%| | 2/19 [00:00Finding shortest conflic| path for python-dateutil[version='>=2.1']:  11%| | 2/1Finding shortest conflict path for python-dateutil[version='>=2.1']:  16%|▏| 3/1Finding shortest- onflict path for ipython[version='>=5.0']:  16%|▏| 3/19 [00:58Finding shortest conflict path for ipython[version='>=5.0']:  21%|▏| 4/19 [00:58Fi\ ing shortest conflict path for python=3.6:  21%|▏| 4/19 [01:07<04:07, 16.51sFinding shortest conflic/ path for python=3.6:  26%|▎| 5/19 [01:07<03:22, 14.47sFinding shortest conflict path for python[version='>=3.6,<3.7.0a0']:  26%|▎| 5/1Finding shortest conflic| path for python[version='>=3.5,<3.6.0a0']:  32%|▎| 6/1Finding shortest conflict path for python[version='>=3.5,<3.6.0a0']:  37%|▎| 7/1Fi| ing shortest conflict path for python=3.7:  37%|▎| 7/19 [01:08<02:02, 10.17sFinding shortest conflict path for python=3.7:  42%|▍| 8/19 [01:08<01:19,  7.23sFinding - ortest conflict path for ipython_genutils:  42%|▍| 8/19 [02:01<01:19, Finding shortest conflict path for ipython_genutils:  47%|▍| 9/19 [02:01<03:28, / nding shortest conflict path for python:  47%|▍| 9/19 [02:11<03:28, 20.87s/it]Finding shortest conflict path for python:  53%|▌| 10/19 [02:11<02:40, 17.83s/itFin- ng shortest conflict path for python=2.7:  53%|▌| 10/19 [02:14<02:40, 17.83Finding shortest conflict p| h for python=2.7:  58%|▌| 11/19 [02:14<01:45, 13.20Finding shortest conflict path for python-dateutil[version='>=2.5.*']:  58%|▌| 1Finding shortest\ onflict path for python[version='>=3.5']:  63%|▋| 12/19 [02:16Finding shortest conflict path for python[version='>=3.5']:  68%|▋| 13/19 [02:16/ nding shortest conflict path for ipython:  68%|▋| 13/19 [02:52<00:57,  9.58s/iFinding shortest conflict path for ipython:  74%|▋| 14/19 [02:52<01:27, 17.52s/iFin\ ng shortest conflict path for python=3.5:  74%|▋| 14/19 [03:02<01:27, 17.52Finding shortest conflict path for python=3.5:  79%|▊| 15/19 [03:02<01:00, 15.18Finding shortest co- lict path for ipython[version='>=4.0.0']:  79%|▊| 15/19 [03Finding shortest conflict path for ipython[version='>=4.0.0']:  84%|▊| 16/19 [03Finding shortest| onflict path for python[version='<=3.3']:  84%|▊| 16/19 [03:12Finding shortest conflict path for python[version='<=3.3']:  89%|▉| 17/19 [03:12Finding shortest conflict- ath for python[version='>=2.7,<2.8.0a0']:  89%|▉| 17/Finding shortest conflict path for python[version='>=2.7,<2.8.0a0']:  95%|▉| 18/Finding shortest| onflict path for python[version='>=3.6']:  95%|▉| 18/19 [03:54Examining certifi:  91%|████████████████████  | 200/220 [05:21<00:21,  1.08s/it]Comparing specs that have this dependency:   0%|          | 0/2 [00:00<?, ?it/s]Finding shortest conf/ ct path for certifi[version='>=2016.09']:   0%| | 0/3 [00Finding shortest conflict path for certifi[version='>=2016.9.26']:  33%|▎| 1/3 [Finding shortest conflict path for ca-certificates:  67%|▋| 2/3 [00:00<00:00, 19Finding shortest conflict path for ca-certificates: 100%|█| 3/3 [00:00<00:00, 29Comparing spe/  that have this dependency:  50%|█ | 1/2 [00:00<00:00,  8.82it/s]Finding shortest conflict path for certifi[version='>=2016.9.26']:   0%| | 0/5 [Finding shortest conf- ct path for certifi[version='>=2017.4.17']:  20%|▏| 1/5 [Finding shortest conflict path for certifi[version='>=2017.4.17']:  40%|▍| 2/5 [Finding shortest co/ lict path for certifi[version='>=2016.09']:  40%|▍| 2/5 [01Finding shortest conflict path for certifi[version='>=2016.09']:  60%|▌| 3/5 \ 1Finding shortest conflict path for certifi:  60%|▌| 3/5 [01:11<00:38, 19.28s/it]Findin| shortest conflict path for ca-certificates:  80%|▊| 4/5 [01:19<00:16, 16failed                                                                                                                                                          UnsatisfiableError: The following specifications were found                     
to be incompatible with the existing python installation in your environment:

Specifications:

  - yank -> python[version='2.7.*|3.5.*|3.6.*']
  - yank -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:



Package setuptools conflicts for:
python=3.7 -> pip -> setuptools
yank -> cython -> setuptools
Package pip conflicts for:
python=3.7 -> pip
yank -> python=2.7 -> pip
Package certifi conflicts for:
yank -> sphinxcontrib-bibtex -> sphinx -> requests -> certifi[version='>=2017.4.17']
yank -> cython -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
Package wheel conflicts for:
yank -> python=2.7 -> pip -> wheel
python=3.7 -> pip -> wheel
Package ca-certificates conflicts for:
yank -> python=2.7 -> ca-certificates
python=3.7 -> openssl[version='>=1.1.1c,<1.1.2a'] -> ca-certificates
Package python-dateutil conflicts for:
yank -> jupyter -> ipykernel -> jupyter_client -> python-dateutil[version='>=2.1']
Package ipython conflicts for:
yank -> jupyter -> ipykernel -> ipython[version='>=4.0|>=4.0.0|>=5.0']

(dynamics) tryinlin@tryinlin-desktop:~$

**Comment by jchodera** [comment]
Can you post the output of 
```bash
$ conda config --show-sources
```
I have a hunch that we don't have the `conda-forge` channel added.

Mine says
```
(orion) lski2838:openmm_orion choderaj$ conda config --show-sources
==> /Users/choderaj/.condarc <==
channels:
  - conda-forge
  - omnia
  - defaults
```
If you don't see `conda-forge` and `omnia`, I'd add them first:
```bash
conda config --add channels omnia --add channels conda-forge
```
then you can create a yank environment:
```bash
conda create --yes -n yank python==3.7 yank
```

**Comment by sawstory** [comment]
Thank you, finally it  worked, now i have to  wait and see outcomes then learn how to analyze the data and then run my own molecules :)
All the best
Omar

**Comment by jchodera** [comment]
Great! I'll close the issue then since we already have https://github.com/choderalab/yank-examples/issues/81 open.

**Comment by sawstory** [comment]
at the end it give me the following error, should i open new issue for that? 
2019-12-03 05:20:17,721: Current Free Energy Estimate is 7.8989536974909775 +- 0.00141414923574307 kT
2019-12-03 05:20:17,725: Computing offline free energy estimate took    0.172s
2019-12-03 05:20:17,725: Iteration took 1.831s.
2019-12-03 05:20:17,725: Estimated completion in 0:00:00, at Tue Dec  3 05:20:17 2019 (consuming total wall clock time 0:13:51.498349).
Analyzing data...
Traceback (most recent call last):
  File "/home/tryinlin/anaconda3/envs/yank/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/tryinlin/anaconda3/envs/yank/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/tryinlin/anaconda3/envs/yank/lib/python3.7/site-packages/yank/commands/analyze.py", line 148, in dispatch
    single_run()
  File "/home/tryinlin/anaconda3/envs/yank/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/home/tryinlin/anaconda3/envs/yank/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/home/tryinlin/anaconda3/envs/yank/lib/python3.7/site-packages/yank/commands/analyze.py", line 143, in single_run
    output = analyze.analyze_directory(args['--store'], **analyzer_kwargs)
  File "/home/tryinlin/anaconda3/envs/yank/lib/python3.7/site-packages/yank/analyze.py", line 782, in analyze_directory
    auto_experiment_analyzer = ExperimentAnalyzer(source_directory, **analyzer_kwargs)
  File "/home/tryinlin/anaconda3/envs/yank/lib/python3.7/site-packages/yank/analyze.py", line 297, in __init__
    raise RuntimeError(err_msg)
RuntimeError: Cannot find analysis.yaml script in p-xylene-implicit-output
Exception ignored in: <function ExperimentAnalyzer.__del__ at 0x7fd28ade5158>
Traceback (most recent call last):
  File "/home/tryinlin/anaconda3/envs/yank/lib/python3.7/site-packages/yank/analyze.py", line 336, in __del__
    for phase, analyzer in self.analyzers.items():
AttributeError: 'ExperimentAnalyzer' object has no attribute 'analyzers'
(yank) tryinlin@tryinlin-desktop:~/anaconda3/pkgs/yank-examples-1.1.0-0/share/yank/examples/binding/t4-lysozyme$

**Comment by jchodera** [comment]
I'll reopen this and let @jaimergp and @andrrizzi look into this.

**Comment by andrrizzi** [comment]
Hi @sawstory . It looks that there are still some installation problems. What happens if you do this?
```
conda create --name yank python=3.6
conda activate yank
conda install yank -c conda-force -c omnia
```
see also http://getyank.org/latest/installation.html#release-build.

**Comment by sawstory** [comment]
still the same error, the previous installation of yank with python 3.7 went smooth and all updated libraries installed, now with python 3.6 i still have the same issue. i installed yank with python 3.6 in different env called yank3.6. kindly look at the log file for the run
[log.txt](https://github.com/choderalab/yank/files/3919792/log.txt)

**Comment by sawstory** [comment]
there are many warnings as you can see in the log file before error,  i woder what is the effect of these warnings on result quality, these are some of the warnings:

WARNING - openmmtools.multistate.multistatesampler - Warning: The openmmtools.multistate API is experimental and may change in future releases
dcdplugin) Could not access file 'p-xylene-implicit-output/experiments/trailblaze/solvent/coordinates.dcd'.

WARNING - yank.pipeline - TLeap: The unperturbed charge of the unit: 8.000000 is not zero.


WARNING - yank.yank - The requested anisotropic dispersion correction won't be computed since the system is non-periodic.

**Comment by jchodera** [comment]
Could you provide the output of `conda list`?

**Comment by sawstory** [comment]
here is the conda list for both yank (env with python 3.7) and yank3.6 (env with python 3.6)
(base) tryinlin@tryinlin-desktop:~$ conda activate yank
(yank) tryinlin@tryinlin-desktop:~$ conda list
# packages in environment at /home/tryinlin/anaconda3/envs/yank:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
ambermini                 16.16.0                       7    omnia
asn1crypto                1.2.0                    py37_0    conda-forge
atk                       2.32.0               haf93ef1_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.17.0               he1b5a44_1    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
cerberus                  1.3.2                      py_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
cftime                    1.0.4.2          py37hc1659b7_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
clusterutils              0.3.1                    py37_1    omnia
cryptography              2.5              py37hb7f436b_1    conda-forge
curl                      7.64.0               h646f8bb_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.14          py37he1b5a44_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.15.2                   py37_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fftw3f                    3.3.4                         2    omnia
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
gdk-pixbuf                2.36.12           haf2c3b9_1004    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3          py37h6f030ca_1002    conda-forge
gobject-introspection     1.58.2          py37h5503ade_1002    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
gtk2                      2.24.32              h90f3771_0    conda-forge
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        1.1.0                    py37_0    conda-forge
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipython                   7.10.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
latexcodec                1.0.7                      py_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.64.0               h01ee5af_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libopenblas               0.3.7                h5ec1e0e_4    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
libtiff                   4.1.0                hc3755c2_1    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib                3.1.1                    py37_0    conda-forge
matplotlib-base           3.1.1            py37hfd891ef_0    conda-forge
mdtraj                    1.9.3            py37h00575c5_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
mock                      3.0.5                    py37_0    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.3.2                hc856adb_0    conda-forge
mpiplus                   v0.0.1                py37_1000    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.1.2          py37had58050_0    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
numexpr                   2.7.0            py37hb3f55d8_0    conda-forge
numpy                     1.17.3           py37h95a1406_0    conda-forge
numpydoc                  0.9.1                      py_0    conda-forge
openmm                    7.4.0           py37_cuda101_rc_1    omnia
openmmtools               0.19.0                   py37_0    omnia
openmoltools              0.8.4                    py37_1    omnia
openssl                   1.0.2t               h14c3975_0    conda-forge
oset                      0.1.3                      py_1    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.3           py37hb3f55d8_0    conda-forge
pandoc                    2.8.0.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               ha030887_1    conda-forge
parmed                    3.2.0            py37he1b5a44_2    conda-forge
parso                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pdbfixer                  1.6                      py37_0    omnia
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pybtex                    0.22.2                   py37_0    conda-forge
pybtex-docutils           0.2.2                    py37_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pymbar                    3.0.5            py37hc1659b7_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pyrsistent                0.15.6           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pytables                  3.5.2            py37ha1aa75f_0    conda-forge
python                    3.7.0             hd21baee_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.2              py37h516909a_0    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
qt                        5.6.2             hce4f676_1013    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.22.0                   py37_1    conda-forge
scipy                     1.3.2            py37h921218d_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                42.0.2                   py37_0    conda-forge
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.13.0                   py37_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    2.2.2                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-bibtex      1.0.0                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.2.0                h516909a_0    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
yank                      0.25.2                   py37_0    omnia
yank-examples             1.1.0                         0    omnia
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
(yank) tryinlin@tryinlin-desktop:~$  conda activate yank3.6
(yank3.6) tryinlin@tryinlin-desktop:~$ conda list
# packages in environment at /home/tryinlin/anaconda3/envs/yank3.6:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
ambermini                 16.16.0                       7    omnia
attrs                     19.3.0                     py_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.17.0               he1b5a44_1    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cerberus                  1.3.2                      py_0    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.13.2           py36h8022711_0    conda-forge
cftime                    1.0.4.2          py36hc1659b7_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
clusterutils              0.3.1                    py36_1    omnia
cryptography              2.8              py36h72c5cf5_1    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.14          py36he1b5a44_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.15.2                   py36_0    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fftw3f                    3.3.4                         2    omnia
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3          py36h6f030ca_1002    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py36_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        1.1.0                    py36_0    conda-forge
ipykernel                 5.1.3            py36h5ca1d4c_0    conda-forge
ipython                   7.10.1           py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.15.1                   py36_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.2.0                    py36_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.3                    py36_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.6.1                    py36_0    conda-forge
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
latexcodec                1.0.7                      py_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.0           default_hde54327_4    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm9                  9.0.0                hc9558a2_3    conda-forge
libnetcdf                 4.7.1           nompi_h94020b1_102    conda-forge
libopenblas               0.3.7                h5ec1e0e_4    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.9.1                hebb1f50_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py36h516909a_0    conda-forge
matplotlib                3.1.2                    py36_1    conda-forge
matplotlib-base           3.1.2            py36h250f245_1    conda-forge
mdtraj                    1.9.3            py36h1c801a5_1    conda-forge
mistune                   0.8.4           py36h516909a_1000    conda-forge
mock                      3.0.5                    py36_0    conda-forge
more-itertools            8.0.0                      py_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.3.2                hc856adb_0    conda-forge
mpiplus                   v0.0.1                py36_1000    conda-forge
nbconvert                 5.6.1                    py36_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.3           nompi_py36hfee4bf2_101    conda-forge
notebook                  6.0.1                    py36_0    conda-forge
nspr                      4.24                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numexpr                   2.7.0            py36hb3f55d8_0    conda-forge
numpy                     1.17.3           py36h95a1406_0    conda-forge
numpydoc                  0.9.1                      py_0    conda-forge
openmm                    7.4.1           py36_cuda101_rc_1    omnia
openmmtools               0.19.0                   py36_0    omnia
openmoltools              0.8.4                    py36_1    omnia
openssl                   1.1.1d               h516909a_0    conda-forge
oset                      0.1.3                      py_1    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.3           py36hb3f55d8_0    conda-forge
pandoc                    2.8.0.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parmed                    3.2.0                    py36_0    omnia
parso                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pdbfixer                  1.6                      py36_0    omnia
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       19.3.1                   py36_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pybtex                    0.22.2                   py36_0    conda-forge
pybtex-docutils           0.2.2                    py36_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pymbar                    3.0.5            py36hc1659b7_0    conda-forge
pyopenssl                 19.1.0                   py36_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
pyqt                      5.12.3           py36hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.6           py36h516909a_0    conda-forge
pysocks                   1.7.1                    py36_0    conda-forge
pytables                  3.6.1            py36h9f153d1_0    conda-forge
python                    3.6.7             h357f687_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.2              py36h516909a_0    conda-forge
pyzmq                     18.1.1           py36h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
scipy                     1.3.2            py36h921218d_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                42.0.2                   py36_0    conda-forge
six                       1.13.0                   py36_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    2.2.2                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-bibtex      1.0.0                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
terminado                 0.8.3                    py36_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.3            py36h516909a_0    conda-forge
traitlets                 4.3.3                    py36_0    conda-forge
urllib3                   1.25.7                   py36_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
widgetsnbextension        3.5.1                    py36_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
yank                      0.25.2                   py36_0    omnia
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
(yank3.6) tryinlin@tryinlin-desktop:~$

**Comment by andrrizzi** [comment]
Hi @sawstory . Just noticed this in your log
```
RuntimeError: Cannot find analysis.yaml script in p-xylene-implicit-output
```
I think the `output_dir` option in the YAML and the `yank analysis --store=DIRECTORY_PATH` are different. If not could you check what's the content of the `p-xylene-implicit-output` folder?

**Comment by sawstory** [comment]
Thanks for your time, i notice that error line too but as you know the output directory created automatically by the run itself, so should i edit the example file run-p-xylene-implicit.sh? 
the analysis.yaml file exist in p-xylene-implicit-output/experiments/ folder not directly in p-xylene-implicit-output folder
this is the content of the run-p-xylene-implicit.sh file
#!/bin/bash

#
# p-xylene binding to T4 lysozyme L99A example run script (serial mode)
#

# Run the simulation
echo "Running simulation..."
yank script --yaml=p-xylene-implicit.yaml

# Analyze the data
echo "Analyzing data..."
yank analyze --store=p-xylene-implicit-output

i guess i should edit the last line to be yank analyze --store=p-xylene-implicit-output/experiments
dose that sound right?
I will try it anyway and see what happen
All the best
Omar

**Comment by andrrizzi** [comment]
Correct. The `--store` option should point to the folder where the netcdf file is stored.

**Comment by sawstory** [comment]
Thanks , it worked :), can you please comment about the warnings below if they normal and dont affect the run?

WARNING - yank.pipeline - TLeap: The unperturbed charge of the unit: 8.000000 is not zero.

WARNING - yank.yank - The requested anisotropic dispersion correction won't be computed since the system is non-periodic.

**Comment by andrrizzi** [comment]
You're welcome! Those warnings are expected with an implicit solvent model. Closing this for now then.
